# Generated by Django 2.0.6 on 2018-06-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_ID',
            field=models.IntegerField(default=0),
        ),
    ]
