# Generated by Django 2.0.6 on 2018-06-28 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0002_activity_activity_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_ID',
        ),
    ]
