# Generated by Django 2.0.6 on 2018-07-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0004_activity_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_time',
            field=models.TimeField(),
        ),
    ]
