# Generated by Django 2.0.6 on 2018-07-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0005_auto_20180720_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_time',
            field=models.DurationField(),
        ),
    ]
