# Generated by Django 2.0.6 on 2018-07-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0006_auto_20180726_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_time',
            field=models.CharField(max_length=50),
        ),
    ]
