# Generated by Django 2.0.6 on 2018-08-17 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0007_auto_20180727_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_time',
            field=models.CharField(default='0000:00:00.000', max_length=50),
        ),
    ]
