# Generated by Django 2.0.6 on 2018-08-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0008_auto_20180816_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
