# Generated by Django 2.0.6 on 2018-08-21 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0009_activity_activity_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='activity',
            name='document',
            field=models.FileField(default='none', upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
