# Generated by Django 2.0.6 on 2018-08-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0010_auto_20180821_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='document',
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_image',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
