# Generated by Django 2.0.6 on 2018-08-22 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0012_activity_cropping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='cropping',
        ),
    ]
